version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # El frontend será accesible en el puerto 80
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000" # El backend será accesible en el puerto 3000
    volumes:
      - ./db.json:/app/db.json # Asegurar que la base de datos JSON sea persistente
