# Usa una imagen base de Node.js
FROM node:18

# Configurar el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios para instalar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código al contenedor
COPY . .

# Exponer el puerto donde correrá el servidor
EXPOSE 5000

# Ejecutar el script "server" para iniciar JSON Server
CMD ["npm", "run", "server"]

